### PR TITLE
New texture and added inf lava cell

### PR DESCRIPTION
**Pull request by EnderProyects**
Added inf lava cell and 2 new textures, one for the water one, and other for the lava one, here I need help in the alocated code to call for the new textures instead of the old one
Part of the code from: https://github.com/GTNewHorizons/AE2FluidCraft-Rework/pull/189
image

Need to add a recipe in coremod for the lava one, magic gated of course
image

### CODE REVIEW

**Comment by EnderProyects** [comment]
The new textures are part of the pr, but can also send them here so they are eassy to see
fluid_storage water
fluid_storage lava

**Comment by EnderProyects** [comment]
> Lava cell is not something we want in the pack, please remove it from this PR and make this just the water cell texture (nice texture on that btw)

Inf lava is as simple as ataching a storage bus to a container that pulls from a Everburn Urn ( Ev gated) I dont see why it should be a problem to have a cell later in the game +UV since tantalite is not a problem at that stage, and I dont thing somebody will make an array of Vulcan geothermal Engines just to power its base

**Comment by LazyFleshWasTaken** [comment]
> > Lava cell is not something we want in the pack, please remove it from this PR and make this just the water cell texture (nice texture on that btw)
> 
> Inf lava is as simple as ataching a storage bus to a container that pulls from a Everburn Urn ( Ev gated) I dont see why it should be a problem to have a cell later in the game +UV since tantalite is not a problem at that stage, and I dont thing somebody will make an array of Vulcan geothermal Engines just to power its base

The problem is the near-infinite throughput of such a cell. It can be abused for limitless power.

**Comment by EnderProyects** [comment]
> Lava cell is not something we want in the pack, please remove it from this PR and make this just the water cell texture (nice texture on that btw)

P.d this pr can be merged since the default recipe is not loaded in the pack, so at least the cell is for creative mode use or future ussage

**Comment by serenibyss** [comment]
Creative fluid cell exists for that purpose

**Comment by EnderProyects** [comment]
Closing this pr and creating a new one just for the texture

**Pull request closed without merging**
