### PR TITLE
Add Fluid Void Cell

### PR DESCRIPTION
**Pull request by lordIcocain**
image

Recipe

image

### CODE REVIEW

**Review by chochem — COMMENTED** [review]
the naming is very inconsistent with the item variant

**Comment by C0bra5** [comment]
I would suggest putting the fact that it's a defective fluid singularity rather than the name on the tooltip.

**Review by serenibyss — CHANGES_REQUESTED** [review]
I agree with earlier comments that the name of this should change to be in line with the other void cell

**Comment by lordIcocain** [comment]
Defective Fluid Digital Singularity is dead

**Review by serenibyss — APPROVED** [review]

**Pull request merged**
