### PR TITLE
fix incorrect fluid caching

### PR DESCRIPTION
**Pull request by Glease**
Close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14620

### CODE REVIEW

**Comment by Glease** [comment]
I don't have a production ae2 system with enough fluid craft pattern to replicate the original problem, so please test with great care

**Review by Pxx500 — APPROVED** [review]
Tested in game, seems to fix the problem with blocking mode and fluid only recipes

Testing performed in kevlar line with all patterns with the same circuit in one chem reactor with blocking mode, also rested with a few manual fluid requests.

**Comment by AbdielKavash** [comment]
I have also tested the example setup from my ticket, and it appears to work as expected now! 🎉

**Comment by Glease** [comment]
I still have a bit of doubts as I cannot test it myself. In any case, we can always revisit this issue later if it did turn out to be problematic.

**Pull request merged**
