### PR TITLE
Add unlocalized names to fluid drops&packets

### PR DESCRIPTION
**Pull request by eigenraven**
Previously they were null in case of drops & not fluid-specific for packets.

Fixes <https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12874>

### CODE REVIEW

**Review by firenoo — COMMENTED** [review]
maybe a nit: Separate the gradle update to its own commit so its easier to track potential future bugs

**Comment by Dream-Master** [comment]
@firenoo can we merge it ?

**Comment by firenoo** [comment]
IMO its best practice to not have unrelated changes in a single commit, especially for something like making a NPE fix and updating gradle. Probably should've requested changes there instead of a comment, sorry.

**Comment by eigenraven** [comment]
The commits get squashed on merge into one big commit anyway so it only affects reviewing, and imo it's easy enough to skip to the java files with the file pane on the left side in the pr viewer

**Comment by firenoo** [comment]
Alright then.

**Review by firenoo — APPROVED** [review]

**Pull request merged**
