### PR TITLE
fluid terminal support long fluid amount

### PR DESCRIPTION
**Pull request by asdflj**
image

### CODE REVIEW

**Comment by asdflj** [comment]
@GlodBlock

**Comment by GlodBlock** [comment]
does the shift dupe also fixed?

**Comment by asdflj** [comment]
> does the shift dupe also fixed?

shift  click transfer item stack?

**Comment by asdflj** [comment]
> does the shift dupe also fixed?

fixed
动画

**Review by GlodBlock — APPROVED** [review]

**Pull request merged**
