### PR TITLE
disable the substitute in ae2fc pattern

### PR DESCRIPTION
**Pull request by GlodBlock**
make sure substitute is disable in ae2fc pattern.
tested with the qf ae2:
image

### CODE REVIEW

**Comment by BlueWeabo** [comment]
Does this mean AE2FC pattern won't be accepted as a substitute for normal pattern? Or no?

**Comment by GlodBlock** [comment]
currently, yeah.
later when i have enough time, i can dig into it and actually make it work properly.

**Comment by minecraft7771** [comment]
Is there something I don't get here or shouldn't it default to true? With this flag disabled, this pattern can't be used in recursive crafting or no?

**Comment by BlueWeabo** [comment]
With this fix. AE2FC patterns can be crafted it seems, but they can't be used if another pattern has substitution as true.

**Comment by BlueWeabo** [comment]
@GlodBlock the problem is about people not being able to use ae2fc patterns as substitutes in normal patterns by the looks and not being able to craft [](https://discord.com/channels/181078474394566657/234936569360809996/1051853661493538896l)

**Pull request closed without merging**
