### PR TITLE
fix the search strings resetting when changing the terminal size in the interface terminal

### PR DESCRIPTION
**Pull request by Alexdoru**

### CODE REVIEW

**Comment by MCTBL** [comment]
https://github.com/user-attachments/assets/7a94cbd8-1ff3-4461-975d-e6d46ebc6763

search string won't clear now, but it won't show up.

**Comment by Alexdoru** [comment]
this is for the interface terminal only, not the fluid terminal,

this is the interface terminal : 
image

**Comment by MCTBL** [comment]
sry mb

**Review by MCTBL — APPROVED** [review]
nice bug fix, LGTM

**Pull request merged**
