### PR TITLE
Add Fluid Artificial Universe Cell

### PR DESCRIPTION
**Pull request by MCTBL**
Add cell for FC like in this pr: https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/529
Related issue: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16663
image
The number of bytes can't be increased without breaking the limit of long in some places

### CODE REVIEW

**Comment by LazyFleshWasTaken** [comment]
Why is it with 63 types and not 5 like the other aefc multi fluid cells?

**Comment by MCTBL** [comment]
> Why is it with 63 types and not 5 like the other aefc multi fluid cells?

image
because the item cell is 63 types, I prefer make them same

**Comment by S4mpsa** [comment]
Every other multi-fluid cell is only 5 types. There is no reason why this should change.

Also, "Fluid Artificial Universe Cell" is a silly name. I would propose "Artificial Ocean Storage Cell" instead.

**Comment by MCTBL** [comment]
> Every other multi-fluid cell is only 5 types. There is no reason why this should change.
> 
> Also, "Fluid Artificial Universe Cell" is a silly name. I would propose "ME Fluid Quasar Cell" instead.
> 
> Generally, I don't see as much need for this one compared to the item variant. That was added primarily for enabling some fancy automation in Stargate tier instead of as an actual storage option. I'm not aware of any cell-shuffling setups that use fluid cells, so this seems to be primarily for fluid storage, but we have multiple "infinite" options for that already.
> 
> However, if this is added, I can make a recipe for it.

that sounds more reasonable.I was thinking too simply.
QQ_1721811445795

**Review by S4mpsa — APPROVED** [review]
The internal ID being "artificial" instead of "universe" is a bit odd, but otherwise everything looks good to me.
Don't see any reason to not have a fluid variant of the cell.

**Comment by MCTBL** [comment]
> The internal ID being "artificial" instead of "universe" is a bit odd, but otherwise everything looks good to me. Don't see any reason to not have a fluid variant of the cell.

well, I'm not good at naming something, so i just simply use the name from ur pr😂

**Comment by S4mpsa** [comment]
I need to change some other names of the fluid stuff anyways, I'll do that in a separate PR.

**Comment by MCTBL** [comment]
> I need to change some other names of the fluid stuff anyways, I'll do that in a separate PR.
> 
> The internal name of the Item variant is `.Universe` instead of `.artifical` as here, which I was referring to with the comment. `item.appliedenergistics2.ItemExtremeStorageCell.Universe.name=Artificial Universe Cell`

OK, i will change it a bit later

**Pull request merged**
