### PR TITLE
Add thousandth mark for cell tooltips.

### PR DESCRIPTION
**Pull request by MCTBL**

### CODE REVIEW

**Comment by MCTBL** [comment]
image
Make the large number more readable.

**Comment by bombcar** [comment]
I understand what it’s doing but giga milibuckets feels weird. I know the vote went against liters ….

**Comment by MCTBL** [comment]
> I understand what it’s doing but giga milibuckets feels weird. I know the vote went against liters ….

I still haven't noticed that before u mention me.

**Comment by MCTBL** [comment]
Should I add a condition can let it show the unit **l** when it identifies the GregTech, and show up the **mB** when without Greg?

**Comment by Hikari1nVoid** [comment]
> I understand what it’s doing but giga milibuckets feels weird. I know the vote went against liters ….

Hey just treat them as items.That's why AE2FC turns every fluid into fluid drops,isn't it?

**Comment by bombcar** [comment]
It's fine leave it as is.

1 Giga L makes sense (giga liters) but 1 Giga milliBucket is a bit weird, it'd be like kilo centimeters.

**Comment by MCTBL** [comment]
> It's fine leave it as is.
> 
> 1 Giga L makes sense (giga liters) but 1 Giga milliBucket is a bit weird, it'd be like kilo centimeters.

got you now.

**Comment by bombcar** [comment]
> > I understand what it’s doing but giga milibuckets feels weird. I know the vote went against liters ….
> 
> we had one vote in either direction iirc. Anyway, I think its fair to assume that nobody wants Gigamilli for anything. thats just terrible. Guess its not touched here though, just in the pic.

Yeah, as far as this goes, the PR is correct unless anyone sees any other issues. To fix gigamili would require a GTNH-wide formatting tool that can fix it

**Review by Connor-Colenso — APPROVED** [review]

**Pull request merged**
