### PR TITLE
eio conduct compact and fix transfer item and fluid in different dirs

### PR DESCRIPTION
**Pull request by GlodBlock**
fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11489

now the dual interface can work with eio conduct and transfer fluid/item in different directions:
image

### CODE REVIEW

**Comment by asdflj** [comment]
not features, is a bug?
7N$05WJH$~~G$QE~FM7WH~A

**Comment by asdflj** [comment]
> i think it doesn't seem like a feature

AE $AB`7~L5CYQ K}( B3J1

**Comment by Dream-Master** [comment]
> > i think it doesn't seem like a feature
> 
> AE $AB`7~L5CYQ K}( B3J1

do me a favor an translate. I dont speak chinese (guess it is chinese)

**Review by eigenraven — APPROVED** [review]

**Comment by asdflj** [comment]
> > > i think it doesn't seem like a feature
> > 
> > 
> > AE $AB`7~L5CYQ K}( B3J1
> 
> do me a favor an translate. I dont speak chinese (guess it is chinese)

this mean whatever just let them go

**Comment by RaitGamerGR** [comment]
Can it put fluid into ender fluid conduit?

**Comment by GlodBlock** [comment]
> Can it put fluid into ender fluid conduit?

it can

**Pull request merged**
